#!/usr/bin/env python3
"""GitHub-style activity heatmap for README.md — text squares, no images.

Reads events.jsonl (via build.aggregate) and rewrites the block between
ACTIVITY markers in README.md: an emoji-square calendar (weeks as rows,
Mon-Sun as columns, color = phase) plus a daily log table.

Topic per day is a hand-maintained map below (matched against docs/ commit
dates) — there's no automated way to know "what was studied" from time logs
alone, so update TOPICS when a new lesson lands on a new date.
"""
import re
import sys
from datetime import date, timedelta
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from build import load_events, aggregate  # noqa: E402

DIR = Path(__file__).resolve().parent
ROOT = DIR.parent.parent
README = ROOT / "README.md"
MARK_START = "<!-- ACTIVITY:START (auto-generated by .claude/progress/heatmap.py — edit TOPICS there, not here) -->"
MARK_END = "<!-- ACTIVITY:END -->"

# date -> short topic label (hand-maintained; extend when a new lesson date lands)
TOPICS = {
    date(2026, 7, 5): "Repo kickoff, roadmap draft",
    date(2026, 7, 6): "Lessons 01-02 — Python basics, type hints",
    date(2026, 7, 7): "README, voice agent import",
    date(2026, 7, 8): "/lesson-start voice command",
    date(2026, 7, 12): "Lessons 03-05 — NumPy, pandas, viz (work)",
    date(2026, 7, 13): "Lessons 03-07 finalized — NumPy, pandas, viz, Jupyter, git-for-ML — Phase 0 closed",
    date(2026, 7, 14): "Voice pipeline fix",
    date(2026, 7, 18): "Lessons 01-05 — vectors, matrices, eigen, derivatives, gradient descent",
    date(2026, 7, 19): "Lessons 01-02 — sklearn fundamentals, linear regression",
    date(2026, 7, 20): "Diabetes practice + R² visualization attempt",
    date(2026, 7, 21): "Retrieval review",
    date(2026, 7, 24): "Quick touch",
    date(2026, 7, 25): "Lessons 03-04 — logistic regression, classification metrics",
    date(2026, 7, 26): "Quick touch",
    date(2026, 7, 27): "Quick touch",
    date(2026, 7, 28): "Quick touch",
    date(2026, 7, 30): "Lesson 05 — trees/Random Forest (redone)",
    date(2026, 7, 31): "Gradient Boosting — loss functions (session start)",
    date(2026, 8, 3): "Quick touch",
    date(2026, 8, 4): "Gradient Boosting — mechanics (continued)",
    date(2026, 8, 7): "Lesson 06 — Gradient Boosting (closed)",
    date(2026, 8, 8): "Lessons 07-09 — KNN/SVM/NB, regularization/CV, GridSearch/PCA/K-Means — Phase 2 complete",
    date(2026, 8, 9): "Phase 3 start — Lesson 01, perceptron/neuron/MLP",
    date(2026, 8, 11): "Lessons 02-04 — ReLU/backprop, PyTorch intro, optimizers/batching",
    date(2026, 8, 12): "Lesson 05 + meta-session — CNN convolution, sklearn vs PyTorch",
    date(2026, 8, 13): "Lessons 06-09 closed — CNN MNIST, regularization, RNN/LSTM, attention",
    date(2026, 8, 15): "Lesson 10 — multi-head attention, Transformer block",
    date(2026, 8, 16): "Lessons 10-12 closed — tiny char-LM, transfer learning, GPU/MPS — Phase 3 lessons complete",
}

MONTHS = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]
WEEKDAYS_EN = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]

# phase id -> colored square, in roadmap order (matches report palette hues)
PHASE_SQUARES = {
    "phase-0": "🟩", "phase-1": "🟧", "phase-2": "🟪",
    "phase-3": "🟥", "phase-4": "🟦", "phase-5": "🟫", "phase-6": "🟨",
}
EMPTY = "⬜"


def fmt_hm_en(sec):
    sec = int(sec)
    h, m = sec // 3600, sec % 3600 // 60
    return f"{h}h {m:02d}m" if h else f"{m}m"


def build_grid(per_day_sec, per_day_phase, d0, d1):
    """Markdown table: one row per week (Mon-start), one column per weekday."""
    lines = ["| Week of | " + " | ".join(WEEKDAYS_EN) + " |",
             "|---|" + "---|" * 7]
    monday = d0 - timedelta(days=d0.weekday())
    while monday <= d1:
        cells = []
        for dow in range(7):
            d = monday + timedelta(days=dow)
            if d < d0 or d > d1:
                cells.append(" ")
            elif per_day_sec.get(d, 0) > 0:
                cells.append(PHASE_SQUARES.get(per_day_phase.get(d), "⬛"))
            else:
                cells.append(EMPTY)
        label = f"{MONTHS[monday.month - 1]} {monday.day}"
        lines.append(f"| {label} | " + " | ".join(cells) + " |")
        monday += timedelta(days=7)
    return "\n".join(lines)


def build_log(daily):
    lines = ["| Date | Day | Hours | Topic |", "|---|---|---|---|"]
    for d, _, sec, _, _ in daily:
        topic = TOPICS.get(d, "—")
        lines.append(f"| {d.isoformat()} | {WEEKDAYS_EN[d.weekday()]} | {fmt_hm_en(sec)} | {topic} |")
    return "\n".join(lines)


def main():
    per_phase, daily, series = aggregate(load_events())
    if not daily:
        print("No daily data yet.")
        return
    per_day_sec = {d: sec for d, _, sec, _, _ in daily}
    per_day_phase = {d: ph for d, _, _, ph, _ in daily}
    d0, d1 = daily[0][0], max(daily[-1][0], date.today())

    total_sec = sum(per_day_sec.values())
    section = "\n".join([
        MARK_START,
        f"**{fmt_hm_en(total_sec)}** of focused study across **{len(daily)} active days** "
        f"({MONTHS[d0.month - 1]} {d0.day} – {MONTHS[d1.month - 1]} {d1.day}).",
        "",
        build_grid(per_day_sec, per_day_phase, d0, d1),
        "",
        "🟩 Phase 0 · Python & tools&nbsp;&nbsp;🟧 Phase 1 · Math&nbsp;&nbsp;🟪 Phase 2 · Classical ML&nbsp;&nbsp;⬜ rest day",
        "",
        "<details>",
        "<summary><b>Daily log</b> — what happened each day</summary>",
        "",
        build_log(daily),
        "",
        "</details>",
        MARK_END,
    ])

    text = README.read_text(encoding="utf-8")
    pattern = re.compile(re.escape(MARK_START) + r".*?" + re.escape(MARK_END), re.DOTALL)
    if not pattern.search(text):
        print(f"ERROR: ACTIVITY markers not found in {README.name} — add them under the Activity heading first.")
        sys.exit(1)
    README.write_text(pattern.sub(lambda _: section, text), encoding="utf-8")
    print(f"✓ README.md activity section updated: {fmt_hm_en(total_sec)}, {len(daily)} days")


if __name__ == "__main__":
    main()
